obstacle_range: 1.5
raytrace_range: 2.0

# TODO: specify proper footprint
#footprint: [[, y0], [x1, y1], [], [xn, yn]]

robot_radius: 0.25
inflation_radius: 0.35
#
#observation_sources: laser_scan_sensor
#laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: false, clearing: false}
#
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
